Traceback (most recent call last):
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\tornado\web.py", line 1767, in _execute
    result = self.prepare()
             ^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\tornado\web.py", line 3149, in prepare
    self.fallback(self.request)
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\livereload\server.py", line 127, in __call__
    app_response = self.wsgi_app(
                   ^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\server\controllers\image_controller.py", line 324, in download_img
    return send_file(image_path, as_attachment=True, download_name=image.id+'.png', mimetype='image/png')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\flask\helpers.py", line 511, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1SLC\Subco\Casemake\H1\Code\.venv\Lib\site-packages\werkzeug\utils.py", line 428, in send_file
    stat = os.stat(path)
           ^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\1SLC\\Subco\\Casemake\\H1\\Code\\server\\static\\uploads/c3a2b8c3-c6c4-4998-84c0-659e7413dbd2/f6e58901-7b01-4175-9419-63c8b8b8fe08.png'
